name: Interesting Link
description: Share an interesting link
title: "[URL]: "
labels: ["link"]
assignees:
  - appwiz
body:
  - type: markdown
    attributes:
      value: |
        We'll attempt to automatically extract the title and slug when we build the site.
  - type: textarea
    id: commentary
    attributes:
      label: Commentary
      description: Additional commentary about this link
      render: markdown
