name: Interesting Link
description: Share an interesting link
labels: ["link-with-title"]
assignees:
  - appwiz
body:
  - type: input
    id: link-url
    attributes:
      label: URL
      description: URL for this link
    validations:
      required: true
  - type: textarea
    id: link-commentary
    attributes:
      label: Commentary
      description: Additional commentary about this link
      render: Markdown
