name: Interesting Link
description: Share an interesting link
labels: ["link-with-title"]
assignees:
  - appwiz
body:
  - type: input
    id: url
    attributes:
      label: URL
      description: URL for this link
  - type: textarea
    id: commentary
    attributes:
      label: Commentary
      description: Additional commentary about this link
      render: Markdown
